@startuml
class com.example.task_web2.HelloController {
+ WebView webview
+ HTMLEditor htmleditor
+ TextArea textarea
+ TextArea textareaforcode
+ void onOpen(ActionEvent)
- String getFileExtension(File)
- void loadHTML(File)
- void loadText(File)
+ void onSave(ActionEvent)
- void saveToFile(String,File)
+ void onUrlLoad(ActionEvent)
- boolean isValidUrl(String)
+ void applyChanges(ActionEvent)
+ void onChange(ActionEvent)
}
class com.example.task_web2.HelloApplication {
+ void start(Stage)
+ {static} void main(String[])
}


javafx.application.Application <|-- com.example.task_web2.HelloApplication
@enduml